name: PRs auto merge

on:
  pull_request:

jobs:
  pr-automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-automerge-action@v1.3.3
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_SECRET }}
      with:
        merge-method: 'merge' # Pull request merge method: "merge", "squash", "rebase". Default is "squash".
        min-approvals: 0 # Default 2
        base-ref: 'main' # Default 'dev'
